In [24]:
import pandas as pd 
from sklearn.preprocessing  import LabelEncoder
from sklearn.model_selection import train_test_split
c = pd.read_csv(r"C:\Users\KOIN\Downloads\tips.csv")
label = LabelEncoder()
c["sex_log"] = label.fit_transform(c["sex"])
c["day_log"] = label.fit_transform(c["day"])
fetures = ["sex_log","day_log"]
target = ["total_bill"]
X = c[fetures]
y = c[target]
X_train,X_Test,y_train,y_test = train_test_split(X,y,test_size =0.4,random_state = 40)
X_train.head()
y_train.head()

     total_bill
0         16.99
53         9.94
48        28.55
96        27.28
154       19.77

In [25]:
X.head()
y.head()

   total_bill
0       16.99
1       10.34
2       21.01
3       23.68
4       24.59

In [4]:
data = {

    "car id " : [1,2,3,4,5] ,
    
    "make": ["toyota " , "honda " , "toyota " , "ford ", "honda "],

    "color": ["red" , "blue" ,"green " ,"red " ,"red "]
 
}


df = pd.DataFrame(data)

print(df)

   car id      make   color
0        1  toyota      red
1        2   honda     blue
2        3  toyota   green
3        4    ford     red
4        5   honda     red

In [5]:
pip install sklearn.preprocessing

Requirement already satisfied: sklearn.preprocessing in c:\users\koin\anaconda3\lib\site-packages (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
# df = pd.DataFrame(data)


label_encoder = LabelEncoder()

df["make_encoder"] = label_encoder.fit_transform(df["make"])

df

NameError: name 'df' is not defined

In [2]:
df["color_encoder"] = label_encoder.fit_transform(df["color"])

df

NameError: name 'label_encoder' is not defined

In [9]:
data = {

    "name" : ["ashish" ,"deepak","kartik","himanshu","subhan"],

    "make" : ["toyota" , "suzuki" ,"ford" ,"honda" , "tvs"],

    "color": ["red" ,"green" ,"yellow" ,"blue" ,"gray"], 
    
    "price": [100 , 200 , 300, 400, 500]
}

df1 = pd.DataFrame(data)

print(df1)

       name    make   color  price
0    ashish  toyota     red    100
1    deepak  suzuki   green    200
2    kartik    ford  yellow    300
3  himanshu   honda    blue    400
4    subhan     tvs    gray    500

In [10]:
one_data_exmp = pd.get_dummies(df1["make"]  , prefix = "make")

df1 = pd.concat([df1, one_data_exmp] , axis = 1)

df1

,name,make,color,price,make_ford,make_honda,make_suzuki,make_toyota,make_tvs
0,ashish,toyota,red,100,False,False,False,True,False
1,deepak,suzuki,green,200,False,False,True,False,False
2,kartik,ford,yellow,300,True,False,False,False,False
3,himanshu,honda,blue,400,False,True,False,False,False
4,subhan,tvs,gray,500,False,False,False,False,True

In [11]:
ordinary_maping = {"toyota": "T" ,"suzuki" : "S" , "ford" : "F" ,"honda" : "H" , "tvs" : "TVS"}

df1 [ "making_ordinary_maping"] = (df1["make"].map(ordinary_maping) )


df1

,name,make,color,price,make_ford,make_honda,make_suzuki,make_toyota,make_tvs,making_ordinary_maping
0,ashish,toyota,red,100,False,False,False,True,False,T
1,deepak,suzuki,green,200,False,False,True,False,False,S
2,kartik,ford,yellow,300,True,False,False,False,False,F
3,himanshu,honda,blue,400,False,True,False,False,False,H
4,subhan,tvs,gray,500,False,False,False,False,True,TVS

In [12]:
# train test split methods

from sklearn.model_selection import train_test_split

In [1]:
print(df.columns)

"""X = df[['make_Encoded', 'color_Encoded']]  # Features

y = df["car id"]  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)"""

NameError: name 'df' is not defined

In [14]:
print(df.columns)

x = df[["make_Encoder", "color_Encoder"]]
y = df["color"]

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=45
)

Index(['car id ', 'make', 'color', 'make_encoder', 'color_encoder'], dtype='object')

KeyError: "None of [Index(['make_Encoder', 'color_Encoder'], dtype='object')] are in the [columns]"

In [25]:
print(df.columns)

Index(['car id ', 'make', 'color', 'make_encoder', 'color_encoder'], dtype='object')