In [11]:
import pandas as pd 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler,LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [13]:
file = r"C:\Users\KOIN\Downloads\apex.csv"

df = pd.read_csv(file)
df

,Loan_ID,Gender,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1002.0,1.0,0.0,0.0,1.0,0.0,5849.0,0.0,128.0,360.0,1.0,1.0,Y
1,1003.0,1.0,1.0,1.0,1.0,0.0,4583.0,1508.0,128.0,360.0,1.0,3.0,N
2,1005.0,1.0,1.0,0.0,1.0,1.0,3000.0,0.0,66.0,360.0,1.0,1.0,Y
3,1006.0,1.0,1.0,0.0,0.0,0.0,2583.0,2358.0,120.0,360.0,1.0,1.0,Y
4,1008.0,1.0,0.0,0.0,1.0,0.0,6000.0,0.0,141.0,360.0,1.0,1.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,2265.0,1.0,1.0,2.0,0.0,0.0,1993.0,1625.0,113.0,180.0,1.0,2.0,Y
407,2266.0,1.0,1.0,2.0,1.0,0.0,3100.0,1400.0,113.0,360.0,1.0,1.0,Y
408,2272.0,1.0,1.0,2.0,1.0,0.0,3276.0,484.0,135.0,360.0,0.0,2.0,Y
409,2277.0,2.0,0.0,0.0,1.0,0.0,3180.0,0.0,71.0,360.0,0.0,1.0,N
410,2281.0,1.0,1.0,0.0,1.0,0.0,3033.0,1459.0,95.0,360.0,1.0,1.0,Y

In [14]:
df.isnull().sum()
r = df["Loan_Status"].mode()
df.fillna(r,axis=0)

,Loan_ID,Gender,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1002.0,1.0,0.0,0.0,1.0,0.0,5849.0,0.0,128.0,360.0,1.0,1.0,Y
1,1003.0,1.0,1.0,1.0,1.0,0.0,4583.0,1508.0,128.0,360.0,1.0,3.0,N
2,1005.0,1.0,1.0,0.0,1.0,1.0,3000.0,0.0,66.0,360.0,1.0,1.0,Y
3,1006.0,1.0,1.0,0.0,0.0,0.0,2583.0,2358.0,120.0,360.0,1.0,1.0,Y
4,1008.0,1.0,0.0,0.0,1.0,0.0,6000.0,0.0,141.0,360.0,1.0,1.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,2265.0,1.0,1.0,2.0,0.0,0.0,1993.0,1625.0,113.0,180.0,1.0,2.0,Y
407,2266.0,1.0,1.0,2.0,1.0,0.0,3100.0,1400.0,113.0,360.0,1.0,1.0,Y
408,2272.0,1.0,1.0,2.0,1.0,0.0,3276.0,484.0,135.0,360.0,0.0,2.0,Y
409,2277.0,2.0,0.0,0.0,1.0,0.0,3180.0,0.0,71.0,360.0,0.0,1.0,N
410,2281.0,1.0,1.0,0.0,1.0,0.0,3033.0,1459.0,95.0,360.0,1.0,1.0,Y

In [15]:
df.fillna(df.mean(numeric_only=True) , inplace=True)

In [16]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Graduate              0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status          13
dtype: int64

In [17]:

x= df.drop(["Loan_Status"],axis=1)
y = df["Loan_Status"]

In [18]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Graduate',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [19]:
binary = ["Gender"]
numeric = ["Credit_History" ,"Property_Area", "Married" ,"Graduate"]

In [20]:
prepro = ColumnTransformer(
    transformers = [
        ("cat", OneHotEncoder(drop="first") ,binary)
        ,
        ("num" , StandardScaler(), numeric)
    ]
)

In [24]:

# model = Pipeline(steps=[
#     ("preprocessing ", prepro)
#     ,
#     ("classifire" , LogisticRegression())
    
# ])

In [25]:
x_train,x_test,y_train,y_test= train_test_split (x,y , test_size= 0.2 , random_state=45)

In [27]:
model.fit(x_train,y_train)

ValueError: Input contains NaN

In [26]:
model = Pipeline(steps=[
    ("preprocessing ", prepro)
    ,
    ("classifire" , LogisticRegression())
    
])
model

Pipeline(steps=[('preprocessing ',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Gender']),
                                                 ('num', StandardScaler(),
                                                  ['Credit_History',
                                                   'Property_Area', 'Married',
                                                   'Graduate'])])),
                ('classifire', LogisticRegression())])

In [28]:
y_pred = model.predict(x_test)

print("accuracy " , accuracy_score)
print("confusion " , confusion_matrix )

NotFittedError: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.